/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeleteAmountOfLoveArgs } from "./DeleteAmountOfLoveArgs";
import { AmountOfLoveFindManyArgs } from "./AmountOfLoveFindManyArgs";
import { AmountOfLoveFindUniqueArgs } from "./AmountOfLoveFindUniqueArgs";
import { AmountOfLove } from "./AmountOfLove";
import { AmountOfLoveService } from "../amountOfLove.service";

@graphql.Resolver(() => AmountOfLove)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class AmountOfLoveResolverBase {
  constructor(
    protected readonly service: AmountOfLoveService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AmountOfLove",
    action: "read",
    possession: "any",
  })
  async _amountOfLovesMeta(
    @graphql.Args() args: AmountOfLoveFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AmountOfLove])
  @nestAccessControl.UseRoles({
    resource: "AmountOfLove",
    action: "read",
    possession: "any",
  })
  async amountOfLoves(
    @graphql.Args() args: AmountOfLoveFindManyArgs
  ): Promise<AmountOfLove[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AmountOfLove, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AmountOfLove",
    action: "read",
    possession: "own",
  })
  async amountOfLove(
    @graphql.Args() args: AmountOfLoveFindUniqueArgs
  ): Promise<AmountOfLove | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AmountOfLove)
  @nestAccessControl.UseRoles({
    resource: "AmountOfLove",
    action: "delete",
    possession: "any",
  })
  async deleteAmountOfLove(
    @graphql.Args() args: DeleteAmountOfLoveArgs
  ): Promise<AmountOfLove | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
